title: Jorge Roberto
email: jorgerobertof8@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
#baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Jorge Roberto
author-pic: minhafoto.jpg
about-author: Olá! Depois eu escrevo mais coisas! May the force be with you!

# Contact links
email: jorssanf@gmail.com # Add your Email address
linkedin: jorssanf
github: jorssanf # Add your Github handle
twitter: 'jorssanf' # Add your Twitter handle
facebook: jorssanf
instagram: jorssanf

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: jorssanf # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
